/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'bjbgorham' at '4/12/16 11:39 PM' with Gradle 2.2.1
 *
 * @author bjbgorham, @date 4/12/16 11:39 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
